# Generated by Django 4.0 on 2022-02-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_score',
            name='score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
