# Generated by Django 4.0 on 2022-02-28 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('dashboard', '0002_user_score_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_score',
            name='id',
        ),
        migrations.AlterField(
            model_name='user_score',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='score', serialize=False, to='auth.user'),
        ),
    ]
