# Generated by Django 4.0 on 2022-01-02 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to='auth.user')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('profile_picture', models.ImageField(default='uploads/profile_pictures/default.png', upload_to='uploads/profile_pictures')),
                ('gender', models.CharField(choices=[('', 'Choose Your Gender'), ('Male', 'Male'), ('Female', 'Female'), ('Rather Not Say', 'Rather Not Say')], max_length=14)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
