# Generated by Django 4.0 on 2022-02-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_team_github_alter_team_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
